# Generated by Django 4.2.16 on 2026-05-25 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=1000)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("sop", "Standard Operating Procedure"),
                            ("training", "Training Manual"),
                            ("user_guide", "User Guide"),
                            ("validation", "Validation Document"),
                            ("kb", "Knowledge Base Article"),
                            ("general", "General Document"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("version", models.CharField(blank=True, default="1.0", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("chunks_count", models.IntegerField(default=0)),
                ("file_size", models.BigIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "status"],
                        name="documents_d_documen_80b3b1_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="documents_d_created_3b0a51_idx"
                    ),
                ],
            },
        ),
    ]
