# Generated by Django 4.2.16 on 2026-05-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="intent_type",
            field=models.CharField(
                choices=[
                    ("knowledge", "Knowledge (RAG)"),
                    ("database", "Database Query"),
                    ("hybrid", "Hybrid"),
                    ("general", "General"),
                    ("workflow", "Guided Workflow"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
