# Generated by Django 4.2.16 on 2026-05-27 05:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_intent_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workflow_id", models.CharField(max_length=100)),
                ("workflow_name", models.CharField(max_length=200)),
                ("current_step", models.CharField(max_length=100)),
                ("current_step_index", models.IntegerField(default=0)),
                ("collected_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("timed_out", "Timed Out"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "chat_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["chat_session", "status"],
                        name="chat_workfl_chat_se_4efb67_idx",
                    )
                ],
            },
        ),
    ]
